// Auto-generated by Pdoc/sponsors/generate.js — do not edit manually
// Generated: 2026-08-06T21:31:48.454Z
const sponsorData = {
  allTime: [
    {
        "name": "wshrguy",
        "github": "wshrguy",
        "tier": "gold",
        "ratio": 0.36
    },
    {
        "name": "spielist",
        "github": "spielist",
        "tier": "silver",
        "ratio": 0.03
    },
    {
        "name": "Redoregon",
        "github": "Redoregon",
        "tier": "silver",
        "ratio": 0.025
    },
    {
        "name": "BeppeBoppo",
        "github": "BeppeBoppo",
        "tier": "silver",
        "ratio": 0.01
    },
    {
        "name": "jimmietron",
        "github": "jimmietron",
        "tier": "silver",
        "ratio": 0.01
    },
    {
        "name": "SRGWML",
        "github": "SRGWML",
        "tier": "silver",
        "ratio": 0.01
    },
    {
        "name": "BareTread",
        "github": "BareTread",
        "tier": "bronze",
        "ratio": 0.005
    },
    {
        "name": "adven2rer",
        "github": "adven2rer",
        "tier": "bronze",
        "ratio": 0.005
    },
    {
        "name": "Johan Marten",
        "github": null,
        "tier": "bronze",
        "ratio": 0.005
    },
    {
        "name": "as3droid",
        "github": "as3droid",
        "tier": "supporter",
        "ratio": 0.001
    },
    {
        "name": "VinVel",
        "github": "VinVel",
        "tier": "supporter",
        "ratio": 0.001
    },
    {
        "name": "mtg92",
        "github": "mtg92",
        "tier": "supporter",
        "ratio": 0.001
    }
],
  thisMonth: [
    {
        "name": "wshrguy",
        "github": "wshrguy",
        "tier": "gold",
        "ratio": 0.1429
    },
    {
        "name": "spielist",
        "github": "spielist",
        "tier": "bronze",
        "ratio": 0.0071
    },
    {
        "name": "as3droid",
        "github": "as3droid",
        "tier": "supporter",
        "ratio": 0.0014
    },
    {
        "name": "VinVel",
        "github": "VinVel",
        "tier": "supporter",
        "ratio": 0.0014
    },
    {
        "name": "mtg92",
        "github": "mtg92",
        "tier": "supporter",
        "ratio": 0.0014
    }
]
};
