// Auto-generated by Pdoc/sponsors/generate.js — do not edit manually
// Generated: 2026-08-27T20:12:11.744Z
const sponsorData = {
  allTime: [
    {
        "name": "wshrguy",
        "github": "wshrguy",
        "tier": "diamond",
        "subTier": "Diamond",
        "ratio": 0.46
    },
    {
        "name": "spielist",
        "github": "spielist",
        "tier": "silver",
        "subTier": "Silver II",
        "ratio": 0.035
    },
    {
        "name": "Redoregon",
        "github": "Redoregon",
        "tier": "silver",
        "subTier": "Silver II",
        "ratio": 0.025
    },
    {
        "name": "BeppeBoppo",
        "github": "BeppeBoppo",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "jimmietron",
        "github": "jimmietron",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "SRGWML",
        "github": "SRGWML",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "BareTread",
        "github": "BareTread",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "adven2rer",
        "github": "adven2rer",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "Johan Marten",
        "github": null,
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "sergio-asenjo",
        "github": "sergio-asenjo",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "PareTrast",
        "github": "PareTrast",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "kaoneko",
        "github": "kaoneko",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "as3droid",
        "github": "as3droid",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.003
    },
    {
        "name": "VinVel",
        "github": "VinVel",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.002
    },
    {
        "name": "mtg92",
        "github": "mtg92",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.002
    },
    {
        "name": "frostynumeral",
        "github": "frostynumeral",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.001
    }
],
  thisMonth: [
    {
        "name": "wshrguy",
        "github": "wshrguy",
        "tier": "gold",
        "subTier": "Gold II",
        "ratio": 0.1429
    },
    {
        "name": "spielist",
        "github": "spielist",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "sergio-asenjo",
        "github": "sergio-asenjo",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "PareTrast",
        "github": "PareTrast",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "kaoneko",
        "github": "kaoneko",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "as3droid",
        "github": "as3droid",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    },
    {
        "name": "VinVel",
        "github": "VinVel",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    },
    {
        "name": "mtg92",
        "github": "mtg92",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    },
    {
        "name": "frostynumeral",
        "github": "frostynumeral",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    }
]
};
