// Auto-generated by .github/scripts/update_downloads.py — do not edit manually
// Generated: 2026-09-22T03:40:47.998436+00:00
const sponsorData = {
  allTime: [
    {
        "name": "wshrguy",
        "github": "wshrguy",
        "tier": "diamond",
        "subTier": "Diamond",
        "ratio": 0.56
    },
    {
        "name": "spielist",
        "github": "spielist",
        "tier": "silver",
        "subTier": "Silver II",
        "ratio": 0.04
    },
    {
        "name": "Redoregon",
        "github": "Redoregon",
        "tier": "silver",
        "subTier": "Silver II",
        "ratio": 0.025
    },
    {
        "name": "q****t",
        "github": null,
        "tier": "silver",
        "subTier": "Silver II",
        "ratio": 0.025
    },
    {
        "name": "BeppeBoppo",
        "github": "BeppeBoppo",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "jimmietron",
        "github": "jimmietron",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "SRGWML",
        "github": "SRGWML",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "sergio-asenjo",
        "github": "sergio-asenjo",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "jurag9999",
        "github": "jurag9999",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.01
    },
    {
        "name": "BareTread",
        "github": "BareTread",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "adven2rer",
        "github": "adven2rer",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "Johan Marten",
        "github": null,
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "PareTrast",
        "github": "PareTrast",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "kaoneko",
        "github": "kaoneko",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "thewalkingcat",
        "github": "thewalkingcat",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.005
    },
    {
        "name": "as3droid",
        "github": "as3droid",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.004
    },
    {
        "name": "VinVel",
        "github": "VinVel",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.003
    },
    {
        "name": "mtg92",
        "github": "mtg92",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.003
    },
    {
        "name": "frostynumeral",
        "github": "frostynumeral",
        "tier": "supporter",
        "subTier": "Supporter II",
        "ratio": 0.002
    }
],
  thisMonth: [
    {
        "name": "wshrguy",
        "github": "wshrguy",
        "tier": "gold",
        "subTier": "Gold II",
        "ratio": 0.1429
    },
    {
        "name": "q****t",
        "github": null,
        "tier": "silver",
        "subTier": "Silver II",
        "ratio": 0.0357
    },
    {
        "name": "jurag9999",
        "github": "jurag9999",
        "tier": "silver",
        "subTier": "Silver I",
        "ratio": 0.0143
    },
    {
        "name": "sergio-asenjo",
        "github": "sergio-asenjo",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "spielist",
        "github": "spielist",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "thewalkingcat",
        "github": "thewalkingcat",
        "tier": "bronze",
        "subTier": "Bronze",
        "ratio": 0.0071
    },
    {
        "name": "frostynumeral",
        "github": "frostynumeral",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    },
    {
        "name": "mtg92",
        "github": "mtg92",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    },
    {
        "name": "VinVel",
        "github": "VinVel",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    },
    {
        "name": "as3droid",
        "github": "as3droid",
        "tier": "supporter",
        "subTier": "Supporter I",
        "ratio": 0.0014
    }
]
};
